org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.java.home=C:/Users/Kazta/jdk17-temurin/jdk-17.0.13+11
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.enabled=false
